### PR TITLE
dev: Remove complex ABI-based logging

### PR DESCRIPTION
**Pull request by smartcontracts**
## Description
Removes the complex parsing we're doing within the EVM. We can easily post-process our data to get this information. Adds too much complexity to do it here.

### Fixes
- Fixes roadmap#743

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](./CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
This LGTM, is there anything blocking us? @tynes

**Comment by tynes** [comment]
People developing with `optimism-integration` are currently using these log messages to know what contracts are being called. Slight regression in UX since the names of the predeploys are no longer logged

**Review by tynes — APPROVED** [review]
There is no obvious place to know what predeploy contract addresses are what as well as what method is being called. This was helpful for people failing the safety checker

**Comment by smartcontracts** [comment]
Going to merge this but will make a note that we need to improve our logging here eventually.

**Pull request merged**
